# Generated by Django 3.1.7 on 2021-03-23 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField()),
                ('short_code', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('last_redirect', models.DateTimeField(auto_now_add=True, null=True)),
                ('redirect_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
